sdkversion: 6.0.0
name: FCMTest
version: 1.0
vendor: tauplatform
build: debug
applog: rholog.txt

capabilities:
  - push


iphone:
  configuration: Release
  sdk: latest
  ARCHS_device: ["arm64"]
  enable_bitcode: false 
  provisioning_style: Manual
  # replace this provisioning info to your:
  provisionprofile: "<your provision profile>"
  development_team: "<your team ID>"
  #codesignidentity: "iPhone Developer"
  BundleIdentifier: com.tauplatform.fcmtest
  BundleURLScheme: taufcmtest

android:
  logcatFilter: APP:I StrictMode:I DEBUG:I *:E
  abis:
    - aarch64
    - x86

extensions: ["fcm-push"]

rhobundle:
  exclude_items:
  - thumb.db
